name: Cryptex CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: macos-10.15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20

      - name: Install dependencies
        run: go get -v -t -d ./...

      - name: Run tests
        run: go test -v ./...

#deploy:
#  needs: build
#  runs-on: macos-10.15
#
#  steps:
#    - name: